
drop table mensaje;
drop table sala;


DROP SEQUENCE AUTOSALA;
DROP SEQUENCE AUTO_MENSAJE;


DROP TABLE PRODUCTO_COLOR;
DROP SEQUENCE AUTO_PRO_COLOR;


DROP TABLE CATEGORIA_HIJA;
DROP SEQUENCE AUTO_CATEGORIA_HIJA;


DROP TABLE PRODUCTO_CATEGORIA;
DROP SEQUENCE AUTO_PRO_CATEGORIA;



DROP TABLE CATEGORIA;
DROP SEQUENCE AUTO_CATEGORIA;

DROP TABLE COLOR;
DROP SEQUENCE AUTO_COLOR;


DROP TABLE PRODUCTO;
DROP SEQUENCE AUTO_PRODUCTO



drop table usuario;

drop table tipo_usuario;

DROP SEQUENCE AUTOUSER;


DROP TABLE BITACORA;
DROP SEQUENCE AUTOBITACORA;










/* CREACION DE SALA_USUARIO 

    CREATE TABLE SALA_USUARIO (
        id_sala_usuario     INTEGER NOT NULL,
        sala        INTEGER NOT NULL,
        usuario  INTEGER NOT NULL,
        CONSTRAINT sala_usuario_pk PRIMARY KEY(id_sala_usuario),
        CONSTRAINT sala_fk FOREIGN KEY(sala) REFERENCES SALA(id_sala),
        CONSTRAINT s_usuario_fk FOREIGN KEY(usuario) REFERENCES USUARIO(id_usuario)
    );

    --DESCRIBE SALA_USUARIO;

    /*
    DROP SEQUENCE AUTO_SALA_USUARIO;
    DROP TRIGGER TRIG_SALA_USUARIO;




    --creacio de autoincrement de sala_usuario 
    CREATE SEQUENCE AUTO_SALA_USUARIO
    START WITH 1
    INCREMENT BY 1;

    CREATE TRIGGER TRIG_SALA_USUARIO
    BEFORE INSERT ON SALA_USUARIO
    FOR EACH ROW
    BEGIN
    SELECT AUTO_SALA_USUARIO.NEXTVAL INTO :NEW.id_sala_usuario FROM DUAL;
    END;

*/ 


